config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :editions
  devise_for :admin_accounts, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pages/terms'
  get 'pages/welcome'
  get 'pages/landing'

  devise_for :accounts, controllers: {
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    unlocks: 'accounts/unlocks',
    omniauth_callbacks: 'accounts/omniauth_callbacks',
  }
  devise_scope :account do
    get '/account/', to: 'accounts/accounts#show', as: '/account/'

    root to: 'accounts/accounts#show'

  end

  resources :works do
    member do
      get :attach_file
      post :upload_file
    end
    resources :authors do
      get :select, on: :collection
    end
    resources :works_roles_authors, only: [:create]
  end
  post   '/works/:work_id/works_roles_authors/:author_id/set_role/:id', to: 'works_roles_authors#set_role', as: :set_role_work_role_author
  delete '/works/:work_id/works_roles_authors/remove_author/:id', to: 'works_roles_authors#remove_author', as: :remove_author_work_role_author
  delete '/works/:work_id/works_roles_authors/:author_id/remove_role/:id', to: 'works_roles_authors#remove_role', as: :remove_role_work_role_author
  resources :roles, except: :index do
    post :select, on: :collection
  end

end

app/models/author.rb
class Author < ActiveRecord::Base

  belongs_to :owner, class_name: 'Account'


  has_many :works_roles_authors
  has_many :roles, through: :works_roles_authors, dependent: :destroy do
    #
    # <tt>for_work(work_id, force = false)</tt>
    #
    # this extension allows to select the roles for a specific work, something
    # that is impossible to do with the regular relationship accessors.
    #
    def for_work(work_id, force = false)
      where('works_roles_authors.work_id = ?', work_id)
    end
  end
  accepts_nested_attributes_for :roles

  validates_presence_of :first_name, :last_name, :owner_id

  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  #
  # +display_birth_year+
  #
  def display_birth_year
    self.birth_year.to_s
  end

  #
  # +display_roles_for_work(work_id)+
  #
  # creates a comma separated list of roles
  #
  def display_roles_for_work(work_id)
    self.roles.for_work(work_id).map { |r| r.description }.uniq.sort.join(', ')
  end

end

app/controllers/authors_controller.rb
class AuthorsController < EndUserBaseController
  before_action :set_work_and_author, except: [ :create, :index ]
  before_action :set_work_and_authors, only: [:index]

  # GET /authors
  # GET /authors.json
  def index
  end

  # GET /works/:id/authors/1
  # GET /works/:id/authors/1.json
  def show
  end

  # GET /works/:id/authors/new
  def new
  end

  # GET /works/:id/authors/1/edit
  def edit
  end

  # GET /works/:id/authors/select
  def select
    @authors = []
    @all_authors = Author.all.order('last_name, first_name').uniq
  end

  # POST /works/:id/authors
  # POST /works/:id/authors.json
  def create
    params[:author].update(owner_id: current_account.to_param)
    r_attrs = params[:author].delete(:roles_attributes) || []
    @work = current_account.works.where(params[:work_id]).uniq.first
    @author = @work.authors.new(author_params)

    respond_to do |format|
      if @author.save
        a_attrs = HashWithIndifferentAccess.new(@author.attributes)
        a_attrs.update(roles_attributes: r_attrs)
        @work.update(authors_attributes: [ a_attrs ])
        format.html { redirect_to select_work_authors_path(@work), notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { redirect_to new_work_author_path(@work, @author) }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/:id/authors/1
  # PATCH/PUT /works/:id/authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to work_author_path(@work, @author), notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/:id/authors/1
  # DELETE /works/:id/authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to work_authors_path(@work), notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_work
    @work = current_account.works.find(params[:work_id])
  end

  def set_work_and_author
    set_work
    @author = params.has_key?(:id) && params[:id] ? Author.find(params[:id]) : Author.new
  end

  def set_work_and_authors
    set_work
    @authors = @work.authors.order('last_name, first_name').uniq
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:first_name, :last_name, :birth_year, :bio_en, :bio_it, :owner_id, :work_id, :owner_id,
                                  roles_attributes: [:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def selected_authors_params
    params.require(:author).permit(authors_attributes: [:id])
  end
end

app/views/authors/_author_item.html.erb
<tr>
  <td><%= link_to author_item.full_name, work_author_path(@work, author_item) %></td>
  <td><%= author_item.display_birth_year %></td>
  <td><%= author_item.display_roles_for_work(@work.to_param) %></td>
  <td><%= link_to 'Show', work_author_path(@work, author_item) %></td>
  <td><%= link_to 'Edit', edit_work_author_path(@work, author_item) %></td>
  <td><%= link_to 'Destroy', work_author_path(@work, author_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/authors/_form.html.erb
<%= form_for([@work, @author]) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birth_year %><br>
    <%= f.number_field :birth_year %>
  </div>
  <div class="field">
    <%= f.label :bio_en %><br>
    <%= f.text_area :bio_en %>
  </div>
  <div class="field">
    <%= f.label :bio_it %><br>
    <%= f.text_area :bio_it %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/confirm_selection.html.erb
<!-- to be removed -->

app/views/authors/edit.html.erb
<h1 class="entry-title">Edit Author</h1>

<%= render 'form' %>

<%= link_to 'Back', work_author_path(@work, @author), class:"btn" %>
<%= link_to 'Works', work_path(@work), class:"btn" %>

<hr>

<center>
<%= link_to 'List of Works', works_path, class:"twobtn" %>
&nbsp;&nbsp;&nbsp;&nbsp;
<%# link_to 'Sign out', destroy_account_session_path, class:"twobtn", method: :delete %>
<center>

app/views/authors/index.html.erb
<h1 class="entry-title">List of Authors</h1>



<div class="entry-content">

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth year</th>
      <th>Roles</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'author_item', collection: @authors %>
  </tbody>
</table>

</div>

<%= link_to 'New Author', new_work_author_path(@work), class:"btn" %>

<hr>

<center>
<%= link_to 'List of Works', works_path, class:"twobtn" %>
&nbsp;&nbsp;&nbsp;&nbsp;
<%# link_to 'Sign out', destroy_account_session_path, class:"twobtn", method: :delete %>
<center>

app/views/authors/new.html.erb
<h1 class="entry-title">New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', work_authors_path(@work), class:"btn" %>

<hr>

<center>
<%= link_to 'List of Works', works_path, class:"twobtn" %>
&nbsp;&nbsp;&nbsp;&nbsp;
<%# link_to 'Sign out', destroy_account_session_path, class:"twobtn", method: :delete %>
<center>

app/views/authors/select.html.erb
<h1 class="entry-title">Select an Author</h1>

<div class="entry-content">

Please select one (or more) authors for <span class='work_title'><strong><%= @work.title %></strong></span> from the following list:

<%= form_for(@author, url: select_roles_url) do |f| %>
  <%= f.hidden_field(:work, { value: @work.to_param, name: 'role[work_id]' }) %>
  <div class="field">
    <%= f.label :author %>
    <%= f.collection_select(:id, @all_authors, :to_param, :full_name, {}, { multiple: 'multiple', name: 'role[authors_attributes][][id]' }) %>
  </div>
  <div class="actions">
    <%= f.submit('Confirm selection') %>
  </div>
<% end %>

</div>

Or create more authors as needed:<br />

<%= link_to 'Add new author', new_work_author_path(@work), class:"btn" %>

app/views/authors/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
<br>
  <strong>Last name:</strong>
  <%= @author.last_name %>
<br>
  <strong>Birth year:</strong>
  <%= @author.display_birth_year %>
<br>
  <strong>Bio en:</strong>
  <%= @author.bio_en %>
<br>
  <strong>Bio it:</strong>
  <%= @author.bio_it %>
</p>

<%= link_to 'Edit', edit_work_author_path(@work, @author), class:"btn" %>
<%= link_to 'Back', work_authors_path(@work), class:"btn"%>