config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :editions
  devise_for :admin_accounts, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pages/terms'
  get 'pages/welcome'
  get 'pages/landing'

  devise_for :accounts, controllers: {
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    unlocks: 'accounts/unlocks',
    omniauth_callbacks: 'accounts/omniauth_callbacks',
  }
  devise_scope :account do
    get '/account/', to: 'accounts/accounts#show', as: '/account/'

    root to: 'accounts/accounts#show'

  end

  resources :works do
    member do
      get :attach_file
      post :upload_file
    end
    resources :authors do
      get :select, on: :collection
    end
    resources :works_roles_authors, only: [:create]
  end
  post   '/works/:work_id/works_roles_authors/:author_id/set_role/:id', to: 'works_roles_authors#set_role', as: :set_role_work_role_author
  delete '/works/:work_id/works_roles_authors/remove_author/:id', to: 'works_roles_authors#remove_author', as: :remove_author_work_role_author
  delete '/works/:work_id/works_roles_authors/:author_id/remove_role/:id', to: 'works_roles_authors#remove_role', as: :remove_role_work_role_author
  resources :roles, except: :index do
    post :select, on: :collection
  end

end

app/views/shared/_footer.html.erb
<%# BEWARE: this link cannot go *inside* any sort of container which reconfigures jQuery, because it needs jQuery in order to work! %>
<center>
<% if account_signed_in? %>
  <%= link_to 'Sign out', destroy_account_session_path, { method: :delete, data: { disable_with: 'signing out...' }, class: 'btn', id: 'signout' } %>
<% end %>
</center>

app/views/shared/_header.html.erb
<div class="navigation-wrapper">
  <nav role="navigation" id="site-nav" class="animated drop">
    <ul>
      <li><a href="http://emufest.org/2016-emufest/" >EMUFest 2016</a></li>
      <li><a href="http://emufest.org/about/" >About</a></li>
      <li><a href="http://www.conservatoriosantacecilia.it" target="_blank">Conservatorio S. Cecilia</a></li>
      <li><a href="http://emufest.org/search/" >Search</a></li>
    </ul>
  </nav>
</div><!-- /.navigation-wrapper -->

<!--[if lt IE 9]><div class="upgrade"><strong><a href="http://whatbrowser.org/">Your browser is quite old!</strong> Why not upgrade to a different browser to better enjoy this site?</a></div><![endif]-->

<header class="masthead">
  <div class="wrap">
    <a href="http://www.emufest.org/" class="site-logo" rel="home" title="EMUFest"><img src="http://www.emufest.org/images/E_site-logo_tondo.png" width="200" height="200" alt="EMUFest logo" class="animated fadeInDown"></a>
    <h1 class="site-title animated fadeIn"><a href="http://www.emufest.org/">EMUFest</a></h1>
    <h2 class="site-description animated fadeIn">International Electroacoustic Music Festival</h2>
  </div>
</header><!-- /.masthead -->