config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :editions
  devise_for :admin_accounts, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pages/terms'
  get 'pages/welcome'
  get 'pages/landing'

  devise_for :accounts, controllers: {
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    unlocks: 'accounts/unlocks',
    omniauth_callbacks: 'accounts/omniauth_callbacks',
  }
  devise_scope :account do
    get '/account/', to: 'accounts/accounts#show', as: '/account/'

    root to: 'accounts/accounts#show'

  end

  resources :works do
    member do
      get :attach_file
      post :upload_file
    end
    resources :authors do
      get :select, on: :collection
    end
    resources :works_roles_authors, only: [:create]
  end
  post   '/works/:work_id/works_roles_authors/:author_id/set_role/:id', to: 'works_roles_authors#set_role', as: :set_role_work_role_author
  delete '/works/:work_id/works_roles_authors/remove_author/:id', to: 'works_roles_authors#remove_author', as: :remove_author_work_role_author
  delete '/works/:work_id/works_roles_authors/:author_id/remove_role/:id', to: 'works_roles_authors#remove_role', as: :remove_role_work_role_author
  resources :roles, except: :index do
    post :select, on: :collection
  end

end

app/models/role.rb
require 'EMUForm/role_manager'

module RoleStaticMethods

  def self.included(base)
    base.extend ClassMethods
  end

  module ClassMethods

    EMUForm::RoleManager.static_role_names.each do
      |sr|
      srname = sr.gsub(/\s+/,'').underscore.to_sym
      define_method(srname) { where('description = ?', sr).first }
    end

  end

end

class Role < ActiveRecord::Base
  validates :description, presence: true, uniqueness: true

  has_many :works_roles_authors
  has_many :works, through: :works_roles_authors, source: :work, dependent: :destroy
  has_many :authors, through: :works_roles_authors, source: :author, dependent: :destroy

  include RoleStaticMethods

  class << self

    def static_roles
      where('static = ?', true).order(:description)
    end

    def ordered_all
      all.order('static DESC, description')
    end

  end

end

app/controllers/roles_controller.rb
class RolesController < EndUserBaseController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # POST /roles/select
  # POST /roles/select.json
  def select
    @work = Work.find(role_selection_params[:work_id])
    @authors = Author.find(role_selection_params[:authors_attributes].map { |a| a[:id] unless a[:id].blank? }.compact)
    @roles = Role.ordered_all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_role
    @role = Role.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_params
    params.require(:role).permit(:description)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def role_selection_params
    params.require(:role).permit(:work_id, authors_attributes: [:id])
  end

end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/_select_role.html.erb
<!-- <hr class="author_role_selection_rule" /> -->

<h3><%= select_role.full_name %>:</h3>
<%= form.hidden_field(:id, name: 'works_roles_authors[authors_attributes][][id]', value: select_role.id) %>
<div class="role_selector" id="author_<%= select_role.to_param -%>">
  <%= form.fields_for(:role) do |r_form| %>
      <%= r_form.collection_check_boxes(:roles, roles, :id, :description, {}, { name: 'works_roles_authors[authors_attributes][][roles_attributes][][id]' }) do |b| %>
      <div class="checkbox">
  	    <%= b.check_box(class: 'role_checkbox') %>
  	    <%= b.label(class: 'role_label') %>
      </div>
  	<% end %>
	<% end %>
  <hr>
</div>

app/views/roles/edit.html.erb
<h1 class="entry-title">Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1 class="entry-title">Listing Roles</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1 class="entry-title">New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/select.html.erb
<h1 class="entry-title">Select Roles:</h1>

<span><strong>Select at least one role for each author (you may select all that apply):</strong></span>

<%= form_for(:work_role_author, url: work_works_roles_authors_path(@work)) do |f| %>
  <%= render partial: 'select_role', collection: @authors, locals: { form: f, roles: @roles } %>
  <%= f.button('Submit selection of roles') %>
<% end %>

<br />

<%= link_to 'Back', select_work_authors_path(@work), class:"btn" %>

<hr>

<center>
<%= link_to 'List of Works', works_path, class:"twobtn" %>
&nbsp;&nbsp;&nbsp;&nbsp;
<%# link_to 'Sign out', destroy_account_session_path, class:"twobtn", method: :delete %>
<center>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>