config/routes.rb
Rails.application.routes.draw do

  resources :categories
  resources :editions
  devise_for :admin_accounts, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pages/terms'
  get 'pages/welcome'
  get 'pages/landing'

  devise_for :accounts, controllers: {
    confirmations: 'accounts/confirmations',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    sessions: 'accounts/sessions',
    unlocks: 'accounts/unlocks',
    omniauth_callbacks: 'accounts/omniauth_callbacks',
  }
  devise_scope :account do
    get '/account/', to: 'accounts/accounts#show', as: '/account/'

    root to: 'accounts/accounts#show'

  end

  resources :works do
    member do
      get :attach_file
      post :upload_file
    end
    resources :authors do
      get :select, on: :collection
    end
    resources :works_roles_authors, only: [:create]
  end
  post   '/works/:work_id/works_roles_authors/:author_id/set_role/:id', to: 'works_roles_authors#set_role', as: :set_role_work_role_author
  delete '/works/:work_id/works_roles_authors/remove_author/:id', to: 'works_roles_authors#remove_author', as: :remove_author_work_role_author
  delete '/works/:work_id/works_roles_authors/:author_id/remove_role/:id', to: 'works_roles_authors#remove_role', as: :remove_role_work_role_author
  resources :roles, except: :index do
    post :select, on: :collection
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :editions

  validates_presence_of   :acro, :title_en, :title_it, :description_en, :description_it
  validates_uniqueness_of :acro

  #
  # +full_title+
  #
  # combines the acro along with the english title
  #
  def full_title
    [self.acro, self.title_en].join(': ')
  end

end

app/controllers/categories_controller.rb
class CategoriesController < AdminBaseController
  before_action :set_category, except: [ :create, :index  ]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.to_a
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to category_path(@category), notice: 'Category was successfully created and made current.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { redirect_to new_category_path(@category) }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_path(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = params[:id] ? Category.find(params[:id]) : Category.new
  end

  def category_params
    params.require(:category).permit(:acro, :title_en, :title_it, :description_en, :description_it)
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :acro %><br>
    <%= f.text_field :acro %>
  </div>
  <div class="field">
    <%= f.label :title_en %><br>
    <%= f.text_field :title_en %>
  </div>
  <div class="field">
    <%= f.label :title_it %><br>
    <%= f.text_field :title_it %>
  </div>
  <div class="field">
    <%= f.label :description_en %><br>
    <%= f.text_area :description_en %>
  </div>
  <div class="field">
    <%= f.label :description_it %><br>
    <%= f.text_area :description_it %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="entry-title">Editing Category</h1>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

<%= render 'form' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="entry-title">Listing Categories</h1>

<%= link_to 'New Category', new_category_path %>

<table>
  <thead>
    <tr>
      <th>Acro</th>
      <th>Title en</th>
      <th>Title it</th>
      <th>Description en</th>
      <th>Description it</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.acro %></td>
        <td><%= category.title_en %></td>
        <td><%= category.title_it %></td>
        <td><%= category.description_en %></td>
        <td><%= category.description_it %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1 class="entry-title">New Category</h1>

<%= link_to 'Back', categories_path %>

<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<p>
  <strong>Acro:</strong>
  <%= @category.acro %>
</p>

<p>
  <strong>Title en:</strong>
  <%= @category.title_en %>
</p>

<p>
  <strong>Title it:</strong>
  <%= @category.title_it %>
</p>

<p>
  <strong>Description en:</strong>
  <%= @category.description_en %>
</p>

<p>
  <strong>Description it:</strong>
  <%= @category.description_it %>
</p>